### ISSUE TITLE
SealFisher Roadmap

### ISSUE THREAD

**Issue by Seeloewen** [Seeloewen/SealFisher#1]
This isn't really a "Roadmap", but rather a list of things I want to implement or improve, in no specific order.

- [x] Sell all Button in inventory: Sells all Fish, Shows sell price of every fish. (@Seeloewen) 
- [x] Limit inventory to 10 fish by default buy upgrades for even more storage; doesn't let you fish if you have max fish (@Seeloewen) 
- [x] Add fish archive: Archive specific fish that you want to keep: 10 slots by default, upgradable by achievements, add option to open archive: in archive, add button to add one fish (@Finni08) 
- [x] Achievements: Get achievements to receive money and special items (@Finni08) 
- [x] Shop: Buy new rods, storage upgrades, new baits, new locations (@Seeloewen) 
- [x] Make fish disappear when not being fished in 5 seconds (@Finni08) 
- [x] Make fish location specific (@Finni08) 
- [x] Make fish spawning 1-12 seconds (@Seeloewen) 
- [x] in inventory: list current amount / max amount of fish (@Seeloewen) 
- [x] Improve how inventory works, add multiple reference variables instead of one (@Seeloewen) 
- [x] Add save system (@Seeloewen) 
- [ ] Add changelog and about window (Don't forget License!) --> Also, legal disclaimer: This game does not support the fishing of protected species (@Seeloewen) 
- [ ] Add auto save every few minutes and autosave on close (@Seeloewen) 
- [x] Add statistics menu that shows your player stats like fishing power, bait power, etc. (everything thats saved in the file). (@Finni08) 
- [x] Fix hopefully most of the most obvious bugs, by adding exception handlers, edge cases, etc. (@Seeloewen) 
- [x] Implement max level for rod and bait in shop (@Finni08) 
- [ ] New locations for building and selecting ships  (@Finni08) 
- [ ] Add Storyline with a Tutorial (@Finni08)
- [ ] Add Start window were you can select your save (@Finni08)
- [ ] fish can only fished at specific locations
- [ ] #5  (@Seeloewen)
- [ ] #6  (@Seeloewen)
